### ISSUE TITLE
Fix model methods with parameter name conflicts

### ISSUE THREAD

**Issue by pepijnverburg** [bmd-studio/lassie-api-php#1]
https://github.com/bmd-studio/lassie-api-php/blob/master/lib/Model.php#L29 the two strings should be prefixed with 'model_', otherwise it returns 403.

This happens with specific requests, for example:
create_event has a "name" field which conflicts with it

**Comment by cyrilmengin** [comment]
Correction for the fix; the two strings should be `model_name` and `method_name` (i.e., postfix `_name`, not the other way around).
